name: Executar script

on: 

  workflow_dispatch:
    inputs:
      ambiente:
        type: environment

      name:
        default: Vieira
        required: true
      Apelido: 
        default : Danho 
        required: true 
        
      opcao:
        type: boolean
        description: Confirme a execução!
        
      Cidade: 
        type: Choise
        option:
        - Lisboa
        - Braga
        - Porto
        - Coimbra
      

jobs: 
  build: 
    runs-on: ubunto-latest
    
